import mysql.connector

conexao = mysql.connector.connect(
    host='172.16.2.95',
    port='3308',
    user='root',
    password='1234',
    database='G2S',
)
cursor = conexao.cursor()

# 1 - Eletricas
# 2 - Mecânicas

dicio = [
    {
        "1": "Acionado direto",
        "2": "Alcance",
        "3": "Ct atraca ñ parte",
        "4": "Micro queimado",
        "5": "Defeito na memoria",
        "6": "Ct ñ aciona embr",
        "7": "Trafo queimado",
        "8": "Ct quebrada",
        "9": "Rele colado",
        "10": "Comp. Em curto",
        "11": "Comp. Invertido",
        "12": "Curto na trilha",
        "13": "Defeito de produção",
        "14": "Comp. Errado",
        "15": "Rele queimado",
        "16": "Solda fria",
        "17": "Sem defeito",
        "18": "Trilha rompida",
        "19": "Terminal dobrado",
        "20": "Fora de frequencia",
        "21": "Falha na gravação",
        "22": "Curto de solda",
        "23": "Ct não aciona",
        "24": "Bateria fraca",
        "25": "Faltando componente",
        "26": "Danificada por raio",
        "27": "Ligação errada",
        "28": "6p20 queimado",
        "29": "Terminais oxidados",
        "30": "Comp. danificado",
        "31": "Bc queimado",
        "32": "Iram com defeito",
        "33": "Modulo queimado",
        "34": "Viper com defeito",
        "35": "Triac queimado",
        "36": "Capacitor queimado",
        "37": "Diodo queimado",
        "38": "Led queimado",
        "39": "Base com defeito",
        "40": "Foto queimado",
        "41": "Microindutor queimado",
        "42": "Borne danificado",
        "43": "Zenner queimado",
        "44": "Haste com defeito",
        "45": "Chave cont. com defeito",
        "46": "Transistor queimado",
        "47": "Fusível queimado",
        "48": "Resistor queimado",
        "49": "Botão com defeito",
        "50": "Trimpot com defeito",
        "51": "Regulador queimado",
        "52": "Chave tactil c/defeito",
        "53": "Frente com defeito",
        "54": "Moc queimado",
        "55": "Trimmer com defeito",
        "56": "CI queimado",
        "57": "Módulo sem alcance",
        "58": "Ponte retificadora queimada",
        "59": "Atualização do software",
        "60": "Atualização de componentes",
        "61": "Diac queimado",
        "62": "Ressonador Queimado",
        "63": "Chame Mini 10/220 Em Curto",
        "64": "Ampola Quebrada",
        "65": "Flat Danificado",
        "66": "Componente alto",
        "67": "Rele não parte",
        "68": "Defeito na botoeira",
        "69": "Defeito no terminal",
        "70": "SMD inserido errado, torto",
        "71": "Faltando solda",
        "72": "Corrosão",
        "73": "Central não parte",
        "74": "TRANSISTOR BC DISCRETO QUEIMADO",
        "75": "TRANSISTOR BC SMD QUEIMADO",
        "76": "TRIAC DISCRETO QUEIMADO",
        "77": "TRIAC SMD QUEIMADO",
        "78": "CAPACITOR ELETROLITICO QUEIMADO",
        "79": "CAPACITOR CERÂMICO DISCRETO QUEIMADO",
        "80": "CAPACITOR CERÂMICO SMD QUEIMADO",
        "81": "CAPACITOR POLYESTER QUEIMADO",
        "82": "DIODO DISCRETO QUEIMADO",
        "83": "DIODO SMD QUEIMADO",
        "84": "LED DISCRETO QUEIMADO",
        "85": "LED SMD QUEIMADO",
        "86": "DIODO ZENNER DISCRETO QUEIMADO",
        "87": "DIODO ZENER SMD QUEIMADO",
        "88": "RESISTOR SMD QUEIMADO",
        "89": "RESISTOR DISCRETO QUEIMADO",
        "90": "REGULADOR DISCRETO QUEIMADO",
        "91": "REGULADOR SMD QUEIMADO",
        "92": "MOC DISCRETO QUEIMADO",
        "93": "MOC SMD QUEIMADO",
        "94": "CI SMD QUEIMADO",
        "95": "CI DISCRETO QUEIMADO",
        "96": "PONTE RETIFICADORA  SMD QUEIMADA",
        "97": "PONTE RETIFICADORA DISCRETA QUEIMADA",
        "98": "IGBT QUEIMADO",
        "99": "DRIVE QUEIMADO",
        "100": "CENTRAL SEM CONSERTO",
        "101": "TENSAO DA CENTRAL",
        "102": "MODELO DA MAQUINA"
    },
    {
        "1": "DESGASTE DE COROA",
        "2": "CARENAGEM QUEBRADA",
        "3": "ENGRENAGEM QUEBRADA",
        "4": "DESGASTE DE PEÇAS",
        "5": "SEM DEFEITO/FALTANDO PEÇAS",
        "6": "CARCAÇA KDZ QUEBRADA",
        "7": "CARCAÇA DZ ANTIGA QUEBRADA",
        "8": "TAMPA DA BASE QUEBRADA",
        "9": "BARULHO NO MOTOR",
        "10": "MÁQUINA DESMONTADA",
        "11": "MOTOR SEM FORÇA",
        "12": "MOTOR CARCACIANDO",
        "13": "MOTOR COM HIPOT",
        "14": "MOTOR COM INFILTRAÇÃO",
        "15": "MOTOR/ESTATOR ABERTO",
        "16": "MOTOR/ESTATOR SEM PARTIDA",
        "17": "CARCAÇA DZ ALUMÍNIO QUEBRADA",
        "18": "FUSO MENOR",
        "19": "ESTATOR / MOTOR FRACO",
        "20": "ACIONAMENTO QUEBRADO",
        "21": "MOTOR COM FUGA",
        "22": "MÁQUINA TRAVADA",
        "23": "PORCA ACIONADORA QUEBRADA",
        "24": "TAMPA DO MOTOR S/ PE PARA ROL. QUEBRADO",
        "25": "CARCAÇA DZ ALUMINIO ESPANADA",
        "26": "MOTOR/ESTATOR QUEIMADO",
        "27": "TAMPA DO MOTOR DZ ALUMINIO QUEBRADO",
        "28": "MAQUINA VEIO DESMONTADA",
        "29": "BARULHO NO ROLAMENTO",
        "30": "PEÇAS DANIFICADA",
        "31": "VAZANDO OLEO",
        "32": "ESTATOR DANDO CHOQUE",
        "33": "ESTATOR EM CURTO",
        "34": "BUCHA DE JUNCAO ESPANADA",
        "35": "ESTATOR COM FIOS CORTADOS",
        "36": "CHAVE DO DESTRAVAMENTO RUIM",
        "37": "PROBLEMA NA LINHA DE MONTAGEM",
        "38": "BARULHO DE COROA",
        "39": "CAPA DO ROLAMENTO DOBRADA",
        "40": "CARCAÇA  ALUMINIO MANCAL QUEBRADA",
        "41": "COPO DO MOTOR QUEBRADA",
        "42": "CARCAÇA RABICHO QUEBRADO",
        "43": "CONJUNTO  ENGRENADO/ENGRENAGEM QUEBRADO",
        "44": "CARCAÇA ALUMINIO MANCAL QUEBRADA",
        "45": "ESTATOR COM FASE QUEIMADA",
        "46": "COROA SEM GRAXA",
        "47": "MÁQUINA COM TRILHO ABERTO",
        "48": "MÁQUINA COM DEFEITO NA CENTRAL ELETRONIC",
        "49": "MÁQUINA NÃO ENTRA NO MANUAL",
        "50": "MÁQUINA COM O ESTATOR ERRADO",
        "51": "INDUZIDO CORRIDO",
        "52": "MÁQUINA COM FUSO ERRADO",
        "53": "FIM DE CURSO COM DEFEITO",
        "54": "ATUALIZAÇÃO DA MÁQUINA",
        "55": "EIXO DE TRAÇÃO QUEBRADO",
        "56": "TAMPA DA CENTRAL QUEBRADA",
        "57": "BASE DA CENTRAL QUEBRADA",
        "58": "CHAVETA QUEBRADA",
        "59": "TAMPA DO MOTOR IND. QUEBRADA",
        "60": "FUSO TORTO",
        "61": "SEM FIM RUIM / BARULHO",
        "62": "FOLGA NO EIXO DE TRAÇÃO",
        "63": "CARCAÇA DE ALUM. BV QUAD ESPANADA",
        "64": "RODA PIVO ROBO TORTA",
        "65": "TRILHO TORTO",
        "66": "COROA OVAL",
        "67": "CARCAÇA ALUM. MANCAL/RABICHO ESQ. QUEBRA",
        "68": "MÁQUINAS COM PEÇAS ERRADAS",
        "69": "ENGRENAGEM PILOTO GASTA",
        "70": "BARULHO DE MOLA FREIO",
        "71": "MOTOR COM INDUÇÃO",
        "72": "INDUZIDO FORA DE CENTRO",
        "73": "ESTATOR BV AQUECENDO DE MAIS",
        "74": "CARCAÇA INDUSTRIAL QUEBRADA",
        "75": "BUCHA DE JUNÇÃO QUEBRADA",
        "76": "MÁQUINA ALTERADA PELO CLIENTE",
        "77": "TAMPA DA BASE DO REDUTOR KDZ QUEBRADA",
        "78": "DEFEITO NO DESTRAVAMENTO",
        "79": "TAMPA DO MOTOR DZ NYLUN/PRICE QUEBRADA",
        "80": "MÁQUINA PARA TROCA",
        "81": "ALAVANCA DO DESTRAVAMENTO QUEBRADA",
        "82": "INDUZIDO INDUSTRIAL COM O SEM FIM RUIM",
        "83": "TAMPA DO REDUTOR INDUSTRIAL QUEBRADA",
        "84": "MÁQUINA NÃO ENTRA NO AUTOMÁTICO",
        "85": "MÁQUINA PEGOU FOGO - DEFEITO NÃO IDENTIF",
        "86": "MÁQUINA SEM GRAXA",
        "87": "CARCAÇA ALUM. BV QUAD QUEBRADA",
        "88": "ESTATOR COM O PACOTE TORTO",
        "89": "CONTRA EMBOLO GASTO",
        "90": "ERRO DA EXPEDIÇÃO - ENVIOU VOLTAGEM ERRA",
        "91": "MOLA DA ESCOVA COM DEFEITO",
        "92": "INSTALAÇÃO DA MÁQUINA INCORRETA",
        "93": "MÁQUINA PESADA",
        "94": "CARCAÇA ALUMINIO PV QUAD QUEBRADA",
        "95": "MÁQUINA ENFERRUJADA",
        "96": "PINO DO DESTRAVAMENTO RUIM",
        "97": "DEFEITO NO FILTRO DO MOTOR PSG",
        "98": "ESTATOR COM AMPERAGEM ALTA",
        "99": "ENGRENAGEM GASTA",
        "100": "SEM DEFEITO",
        "101": "MÁQUINA / PEÇAS MANCHADA",
        "102": "CAPACITOR QUEIMADO / FRACO",
        "103": "EIXO DE TRAÇÃO TORTO",
        "104": "MANCAL TRASEIRO DANIFICADO",
        "105": "FALTANDO PEÇAS",
        "106": "PASSO CABO DANIFICADO",
        "107": "TAMPÃO TPD DANIFICADO",
        "108": "FIO ROMPIDO",
        "109": "EIXO FORA DE MEDIDA",
        "110": "MOTOR COM BARULHO",
        "111": "TAMPA TRINCADA",
        "112": "ROTOR COM FALHA",
        "113": "ACABAMENTO NÃO CONFORME",
        "114": "TAMPA COM FOLGA NA BUCHA",
        "115": "CAPACITOR ERRADO",
        "116": "CURTO ENTRE ESPIRAS",
        "117": "VENTOINHA DANIFICADA",
        "118": "FIO EMBOBINADO SOLTO",
        "119": "TAMPA COM REBARBA",
        "120": "EIXO COM REBARBA",
        "121": "COROA FORA DE MEDIDA",
        "122": "EIXO PRINCIPAL DA CANCELA DANIFICADO",
        "123": "FURO TORTO",
        "124": "REED NÃO LÊ O IMÃ",
        "125": "FURO DA AGULHA ESPANADO",
        "126": "PEÇA COM BOLHA",
        "127": "PEÇA FORA DE CENTRO",
        "128": "PINTURA COM FALHA",
        "129": "PEÇA COM REBARBA",
        "130": "AMPERAGEM BAIXA",
        "131": "VENTOINHA EXTERNA PEGANDO NA TAMPA",
        "132": "ALOJAMENTO DO ROLAMENTO FORA DE MEDIDA",
        "133": "ALOJAMENTO DO ROLAMENTO ESTOURADO",
        "134": "ALOJAMENTO DO ROLAMENTO TRINCADO",
        "135": "ROTOR FORA DE MEDIDA",
        "136": "ENGRENAGEM NÃO CONFORME",
        "137": "FURAÇÃO ERRADA",
        "138": "CARCAÇA QUEBRADA",
        "139": "REED COM FIO CURTO",
        "140": "CORPO DA CANCELA DANIFICADO",
        "141": "DENTE DA COROA NÃO CONFORME",
        "142": "MÁQUINA COM RUÍDO",
        "143": "CARCAÇA SEM USINAR",
        "144": "TAMPA DA CENTRAL QUEBRADA",
        "145": "PONTA DO EMBOLO QUEBRADO",
        "146": "PROTEÇÃO DA ENGRENAGEM DZ ALUMÍNIO QUEBR",
        "147": "FLANGE DANIFICADA",
        "148": "COROA QUEBRADA",
        "149": "ARRUELA DE FERRO DANIFICADA",
        "150": "ARRUELA CELERON DANIFICADA",
        "151": "ARRUELA CELERON PILOTO GASTA",
        "152": "BORRACHA DE VEDAÇÃO ROMPIDA",
        "153": "CARCAÇA KDZ ESPANADA",
        "154": "TAMPA DA BASE GRANKDZ ESPANADA",
        "155": "CORREIA FORA DE CENTRO",
        "156": "DEFEITO NA FURAÇÃO DO ROTOR",
        "157": "BUCHA DA JUNCAO ESPANADA",
        "158": "FECHADURA COM DEFEITO MECANICO",
        "159": "FECHADURA FALTANDO PEÇAS",
        "160": "PORTA DE ENROLAR COM DEFEITO ELETRONICO",
        "161": "PORTA DE ENROLAR COM DEFEITO MECANICO"
    }
]

# for i in range(1, len(dicio[0])):
#     print(dicio[0].get(f'{i}'))
#     comando = f'INSERT INTO causes(type,code,description) VALUES ("Elétrico", "{i}", "{dicio[0].get(str(i))}")'
#     cursor.execute(comando);

comandoSelect = f'SELECT * FROM causes'
cursor.execute(comandoSelect)
resultado = cursor.fetchall() # ler o banco de dados

print(resultado)

comandoDelete = f'DELETE FROM causes'
# cursor.execute(comandoDelete)

# conexao.commit()# edita o banco de dados

cursor.close()
conexao.close()